-- WARNING: This script intentionally replaces the existing application tables.
-- Run it in Supabase Dashboard > SQL Editor using a project owner account.

drop table if exists public.template_schedules cascade;
drop table if exists public.flights cascade;
drop table if exists public.flight_templates cascade;
drop table if exists public.airlines cascade;
drop table if exists public.agencies cascade;
drop table if exists public.delay_codes cascade;
drop function if exists public.authenticate_user(text, text);
drop table if exists public.app_users cascade;

create extension if not exists pgcrypto with schema extensions;

create table public.app_users (
  user_id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('staff', 'manager', 'data-insert', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Allows a project owner to insert a plaintext value into password_hash from
-- the Supabase table editor while ensuring only a bcrypt hash is stored.
create or replace function public.hash_app_user_password()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if new.password_hash is null or new.password_hash = '' then
    raise exception 'password_hash is required';
  end if;

  if new.password_hash not like '$2%' then
    new.password_hash := extensions.crypt(new.password_hash, extensions.gen_salt('bf'));
  end if;

  return new;
end;
$$;

create trigger app_users_hash_password
before insert or update of password_hash on public.app_users
for each row execute function public.hash_app_user_password();

insert into public.app_users (username, password_hash, role) values
  ('staff', extensions.crypt('staff123', extensions.gen_salt('bf')), 'staff'),
  ('manager', extensions.crypt('manager123', extensions.gen_salt('bf')), 'manager'),
  ('data', extensions.crypt('data123', extensions.gen_salt('bf')), 'data-insert'),
  ('admin', extensions.crypt('admin123', extensions.gen_salt('bf')), 'admin');

create or replace function public.authenticate_user(p_username text, p_password text)
returns table (username text, role text)
language sql
security definer
set search_path = public, extensions
as $$
  select u.username, u.role
  from public.app_users u
  where lower(u.username) = lower(trim(p_username))
    and u.password_hash = extensions.crypt(p_password, u.password_hash)
    and u.is_active = true
  limit 1;
$$;

revoke all on table public.app_users from anon, authenticated;
grant execute on function public.authenticate_user(text, text) to anon, authenticated;

create table public.airlines (
  airline_id bigint primary key,
  airline_name text not null,
  iata_code text,
  country text,
  handling_company text,
  created_at timestamptz not null default now()
);

create table public.delay_codes (
  code text primary key,
  category text not null,
  description text not null
);

create table public.agencies (
  agency_id bigint primary key,
  agency_name text not null,
  contact_email text,
  phone text,
  created_at timestamptz not null default now()
);

create table public.flight_templates (
  template_id bigint primary key,
  template_name text not null,
  inbound_flight_number text not null,
  outbound_flight_number text not null,
  sta_time_of_day time not null,
  std_time_of_day time not null,
  origin text not null,
  destination text not null,
  via text,
  final_destination text not null,
  airline_id bigint not null references public.airlines(airline_id) on update cascade,
  agency_id bigint not null references public.agencies(agency_id) on update cascade,
  aircraft_type text not null,
  created_at timestamptz not null default now()
);

create table public.template_schedules (
  schedule_id bigint generated by default as identity primary key,
  template_id bigint not null unique references public.flight_templates(template_id) on delete cascade,
  frequency text not null check (frequency in ('Daily', 'Weekly')),
  days_of_week text not null,
  start_date date not null,
  end_date date not null,
  check (end_date >= start_date)
);

create table public.flights (
  flight_id bigint primary key,
  inbound_flight_number text not null,
  outbound_flight_number text not null,
  sta_utc timestamptz not null,
  std_utc timestamptz not null,
  ata_utc timestamptz,
  atd_utc timestamptz,
  origin text not null,
  destination text not null,
  via text,
  final_destination text not null,
  airline_id bigint not null references public.airlines(airline_id) on update cascade,
  airline_name text not null,
  agency_id bigint not null references public.agencies(agency_id) on update cascade,
  agency_name text not null,
  aircraft_type text not null,
  registration text not null default '',
  remarks text not null default '',
  number_of_bags integer,
  adult_pax integer,
  child_pax integer,
  infant_pax integer,
  total_pax integer,
  delays jsonb not null default '[]'::jsonb,
  flight_status text not null check (flight_status in ('Scheduled', 'Not Arrived', 'Arrived - Not Departed', 'Departed - Not Arrived', 'Not Departed', 'Completed', 'Canceled')),
  cancellation_reason text,
  delay_minutes_total integer not null default 0,
  created_at timestamptz not null default now()
);

create index flights_sta_utc_idx on public.flights(sta_utc);
create index flights_status_idx on public.flights(flight_status);

alter table public.airlines enable row level security;
alter table public.agencies enable row level security;
alter table public.flight_templates enable row level security;
alter table public.template_schedules enable row level security;
alter table public.flights enable row level security;
alter table public.delay_codes enable row level security;

-- The frontend authenticates through authenticate_user and uses these policies
-- for the current application data operations.
create policy "public app access" on public.airlines for all to anon, authenticated using (true) with check (true);
create policy "public app access" on public.agencies for all to anon, authenticated using (true) with check (true);
create policy "public app access" on public.flight_templates for all to anon, authenticated using (true) with check (true);
create policy "public app access" on public.template_schedules for all to anon, authenticated using (true) with check (true);
create policy "public app access" on public.flights for all to anon, authenticated using (true) with check (true);
create policy "public app access" on public.delay_codes for all to anon, authenticated using (true) with check (true);

-- Publish data changes so every open client receives inserts, updates, and deletes immediately.
alter publication supabase_realtime add table public.airlines;
alter publication supabase_realtime add table public.agencies;
alter publication supabase_realtime add table public.flight_templates;
alter publication supabase_realtime add table public.template_schedules;
alter publication supabase_realtime add table public.flights;